### ISSUE TITLE
I get a RuntimeBinderException when trying to setup the inertiaJS with ASP.NET core Abp.io

### ISSUE THREAD

**Issue by nicksoftware** [kapi2289/InertiaCore#11]
I get the following error:

```
RuntimeBinderException: The call is ambiguous between the following methods or properties: 'System.Text.Json.JsonSerializer.Serialize<System.Text.Json.JsonSerializerOptions>(System.IO.Stream, System.Text.Json.JsonSerializerOptions, System.Text.Json.JsonSerializerOptions)' and 'System.Text.Json.JsonSerializer.Serialize<System.Text.Json.JsonSerializerOptions>(System.Text.Json.Utf8JsonWriter, System.Text.Json.JsonSerializerOptions, System.Text.Json.JsonSerializerOptions)'
```

![image](https://github.com/kapi2289/InertiaCore/assets/36539498/5020f965-8cad-4eaf-931d-7204caef356d)

**Comment by kapi2289** [comment]
Hi, can you please provide your code to recreate the error?

**Comment by nicksoftware** [comment]
Hey @kapi2289 , I created a demo [project](https://github.com/nicksoftware/inertiaJS-Abp.Aspnetcore) to share with you and it just worked. I'm guessing it might have been caused by a misconfiguration on my end on the other project. thanks for the quick response though 🙂

**Comment by kapi2289** [comment]
@nicksoftware thanks! If for some reason the problem will reoccur, please let me know and I'll reopen this issue. You don't need to create whole demo project, you can just provide the most important snippets of your code.

In your example i think the problem could have lied in the method invoking the `Inertia.Render` method.
