### ISSUE TITLE
How to handle authorized routes?

### ISSUE THREAD

**Issue by r2r2b1** [kapi2289/InertiaCore#15]
Hello, first of all thank you for maintaining this package. 

I'm using this amazing package in my project but there is a small issue. When **I click an authorized route link as unauthenticated user and it popups blank frame** instead of redirecting me to login page. 

When I enter the URL directly, it redirects me to login page but when I try to access the route through Inertia this issue happens.

Is there a way to handle this issue?

https://github.com/kapi2289/InertiaCore/assets/137212059/5da8db52-e060-4e65-aa6b-f92ad25dbc32

**Comment by chuck-waters** [comment]
What does your Auth setup code look like? Mine is handled with authentication middleware (not inertia middleware) and if they're unauthenticated, they get redirected to the login page.

**Comment by r2r2b1** [comment]
Hi @chuck-waters, I created a new project in its bare-bones form to reproduce the issue: https://github.com/r2r2b1/inertia-unauth-reprod. 

If you run the project you will encounter with the issue. This how the `Program.cs` looks like:

<img width="509" alt="Screenshot 2024-05-25 at 13 20 49" src="https://github.com/kapi2289/InertiaCore/assets/137212059/b3822289-5165-4ea8-87d3-38c867412570">

**Comment by r2r2b1** [comment]
After some research I solved this issue by adding this middleware **before** `app.UseAuthorization()` middleware. 

```cs
app.Use(async (context, next) =>
{
    await next.Invoke();
    if (context.Request.Headers.ContainsKey("X-Inertia") && context.Response.StatusCode == 401)
    {
        context.Response.Redirect($"/Account/Login?returnUrl={Uri.EscapeDataString(context.Request.Path)}");
    }
});
```

 But I think it would be nicer if this middleware came built-in with the package. What do you think?

**Comment by chuck-waters** [comment]
I don’t think that would make sense because not all authentication uses the same routes. I’m using Azure B2C in my apps for authentication and that part is definitely different in my implementation

**Comment by r2r2b1** [comment]
I see. I'm new to ASP.NET and wasn't aware of other authentication options. Thanks for the help.
