### ISSUE TITLE
This project is under developer and can be used in production? 

### ISSUE THREAD

**Issue by antoniomldev** [kapi2289/InertiaCore#18]
Hello everybody.

I've known InertiaJs for a while and I'm happy to have found an adapter for C#/.NET.

I would like to know if the project is still under development and I can use it in a project of mine that will go into production. 

Thanks!

**Comment by adrum** [comment]
@antoniomldev We've been using v1 on the front-end with this adapter for well over a year in Production. It works well.

v2 was just released, and we have not yet released compatibility for v2 in this adapter yet, so stick to v1 for now. I plan to start chipping away at v2 support soon.
