### ISSUE TITLE
Add an sample

### ISSUE THREAD

**Issue by RicardoDev1999** [kapi2289/InertiaCore#9]
Hi, would it be possible to add an sample app? 

That shows how to setup a .NET6 simple project with an vue page?

**Comment by NejcBW** [comment]
You can check this repo: https://github.com/NejcBW/InertiaCoreVueTemplate

Main branch is for the Vue with js implementation, ts branch is for Vue with TypeScript implementation. Check also the readme notes.

**Comment by kapi2289** [comment]
Hi! Thanks @NejcBW for the example. As soon as I merge #8, I'll add to README a few open source examples using InertiaCore, including yours.

**Comment by nicksoftware** [comment]
Here's a React Sample 🙂  https://github.com/nicksoftware/React-AspnetCore-inertiaJS

**Comment by kapi2289** [comment]
Thanks @NejcBW @nicksoftware for your examples. I've included them in README.
